CREATE TABLE board(
	no NUMBER(3) PRIMARY KEY,
	title VARCHAR2(100),
	content VARCHAR2(500),
	author VARCHAR2(100),
	nal VARCHAR2(20),
	readCount NUMBER(3)
);

SELECT * FROM BOARD;
SELECT NO,TITLE,CONTENT,AUTHOR,NAL,READCOUNT FROM BOARD;

