CREATE TABLE HAKSASTD(
	NO NUMBER(10) PRIMARY KEY,
	IRUM VARCHAR2(30),
	AGE VARCHAR2(30),
	HAKBUN VARCHAR2(30)
)

CREATE TABLE HAKSAPROF(
	NO NUMBER(10) PRIMARY KEY,
	IRUM VARCHAR2(30),
	AGE VARCHAR2(30),
	SUBJECT VARCHAR2(30)
)

CREATE TABLE HAKSAMNG(
	NO NUMBER(10) PRIMARY KEY,
	IRUM VARCHAR2(30),
	AGE VARCHAR2(30),
	PART VARCHAR2(30)
)

DROP TABLE HAKSASTD;
DROP TABLE HAKSAPROF;
DROP TABLE HAKSAMNG;